# Ein Modell für alle Messdatensätze

! XBG wird ausgeschlossen

# Vorbereitung

In [1]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

# Laden der CSV-Dateien in separate DataFrames
df_1 = pd.read_csv('/content/drive/MyDrive/results/emissions_full_Heart_Logistic_Regression.csv')
df_2 = pd.read_csv('/content/drive/MyDrive/results/emissions_full_Heart_GaussianNB.csv')
df_3 = pd.read_csv('/content/drive/MyDrive/results/emissions_full_Heart_DecisionTree.csv')

df_4 = pd.read_csv('/content/drive/MyDrive/results/emissions_full_Diabetes_RandomForest.csv')
df_5 = pd.read_csv('/content/drive/MyDrive/results/emissions_full_Diabetes_LogisticRegression.csv')
df_6 = pd.read_csv('/content/drive/MyDrive/results/emissions_full_Diabetes_KNN.csv')
df_8 = pd.read_csv('/content/drive/MyDrive/results/emissions_full_Diabetes_GaussianNB.csv')
df_9 = pd.read_csv('/content/drive/MyDrive/results/emissions_full_Diabetes_DecisionTree.csv')

df_10 = pd.read_csv('/content/drive/MyDrive/results/emissions_full_Bank_RandomForest.csv')
df_11 = pd.read_csv('/content/drive/MyDrive/results/emissions_full_Bank_LogisticRegression.csv')
df_12 = pd.read_csv('/content/drive/MyDrive/results/emissions_full_bank_KNN.csv')
df_13 = pd.read_csv('/content/drive/MyDrive/results/emissions_full_Bank_GaussianNB.csv')
df_14 = pd.read_csv('/content/drive/MyDrive/results/emissions_full_BANK_DCT.csv')

# Alle DataFrames in eine Liste einfügen
dfs = [df_1, df_2, df_3, df_4, df_5, df_6, df_8, df_9, df_10, df_11, df_12, df_13, df_14]

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
 # Definieren der Feature Typen
feature_types = {
    'Diabetes_binary': 'kategorisch',
    'HighBP': 'kategorisch',
    'HighChol': 'kategorisch',
    'CholCheck': 'kategorisch',
    'BMI': 'numerisch',
    'Smoker': 'kategorisch',
    'Stroke': 'kategorisch',
    'HeartDiseaseorAttack': 'kategorisch',
    'PhysActivity': 'kategorisch',
    'Fruits': 'kategorisch',
    'Veggies': 'kategorisch',
    'HvyAlcoholConsump': 'kategorisch',
    'AnyHealthcare': 'kategorisch',
    'NoDocbcCost': 'kategorisch',
    'GenHlth': 'numerisch',
    'MentHlth': 'numerisch',
    'PhysHlth': 'numerisch',
    'DiffWalk': 'kategorisch',
    'Sex': 'kategorisch',
    'Age': 'numerisch',
    'Education': 'numerisch',
    'Income': 'numerisch',
    'age': 'numerisch',
    'job': 'kategorisch',
    'marital': 'kategorisch',
    'education': 'kategorisch',
    'default': 'kategorisch',
    'balance': 'numerisch',
    'housing': 'kategorisch',
    'loan': 'kategorisch',
    'contact': 'kategorisch',
    'day_of_week': 'kategorisch',
    'month': 'kategorisch',
    'duration': 'numerisch',
    'pdays': 'numerisch',
    'previous': 'numerisch',
    'poutcome': 'kategorisch',
    'HeartDisease': 'kategorisch',
    'BMI': 'numerisch',
    'Smoking': 'kategorisch',
    'AlcoholDrinking': 'kategorisch',
    'Stroke': 'kategorisch',
    'PhysicalHealth': 'numerisch',
    'MentalHealth': 'numerisch',
    'DiffWalking': 'kategorisch',
    'Sex': 'kategorisch',
    'AgeCategory': 'kategorisch',
    'Race': 'kategorisch',
    'Diabetic': 'kategorisch',
    'PhysicalActivity': 'kategorisch',
    'GenHealth': 'kategorisch',
    'SleepTime': 'numerisch',
    'Asthma': 'kategorisch',
    'KidneyDisease': 'kategorisch',
    'SkinCancer': 'kategorisch'
}

In [3]:
df_1.head()

,timestamp,project_name,run_id,duration,emissions,emissions_rate,cpu_power,gpu_power,ram_power,cpu_energy,...,gpu_model,longitude,latitude,ram_total_size,tracking_mode,on_cloud,pue,num_features,reduction_percentage,feature_names
0,2023-11-17T08:30:09,LogisticRegression_17_features_reduced_by_0_pe...,caf57cf5-b259-4a2c-bc67-bea00e2a898c,0.445057,7.999063e-07,0.000002,42.5,0.0,4.754376,0.000005,...,NaN,-121.1871,45.5999,12.678337,machine,N,1.0,17,0,"Smoking, BMI, Sex, Diabetic, AlcoholDrinking, ..."
1,2023-11-17T08:30:12,LogisticRegression_17_features_reduced_by_20_p...,6ae977a5-b2fa-449c-9036-12467aec2fd5,0.365585,6.496404e-07,0.000002,42.5,0.0,4.754376,0.000004,...,NaN,-121.1871,45.5999,12.678337,machine,N,1.0,17,20,"Smoking, BMI, Sex, Diabetic, AlcoholDrinking, ..."
2,2023-11-17T08:30:14,LogisticRegression_17_features_reduced_by_40_p...,0830ffc0-0553-48b3-8434-e33dd6eb1be6,0.305748,5.390057e-07,0.000002,42.5,0.0,4.754376,0.000004,...,NaN,-121.1871,45.5999,12.678337,machine,N,1.0,17,40,"Smoking, BMI, Sex, Diabetic, AlcoholDrinking, ..."
3,2023-11-17T08:30:17,LogisticRegression_17_features_reduced_by_60_p...,6eb9c17f-25b6-4576-9073-0beaba830ad3,0.278265,4.933792e-07,0.000002,42.5,0.0,4.754376,0.000003,...,NaN,-121.1871,45.5999,12.678337,machine,N,1.0,17,60,"Smoking, BMI, Sex, Diabetic, AlcoholDrinking, ..."
4,2023-11-17T08:30:19,LogisticRegression_17_features_reduced_by_80_p...,9e90146c-6328-4cff-9a6e-4d6f266fa299,0.227904,3.947965e-07,0.000002,42.5,0.0,4.754376,0.000003,...,NaN,-121.1871,45.5999,12.678337,machine,N,1.0,17,80,"Smoking, BMI, Sex, Diabetic, AlcoholDrinking, ..."

In [4]:
# Mappen der Features auf die Daten
dataframes = [df_1, df_2, df_3, df_4, df_5, df_6, df_8, df_9, df_10, df_11, df_12, df_13, df_14]

for df in dataframes:
  df['num_num_features'] = df['feature_names'].apply(lambda x: sum(1 for feature in x.split(', ') if feature_types.get(feature) == 'numerisch'))
  df['num_cat_features'] = df['feature_names'].apply(lambda x: sum(1 for feature in x.split(', ') if feature_types.get(feature) == 'kategorisch'))

# Ermitteln, wie of ein feature vorgekommen ist

df['feature_names'] = df['feature_names'].str.split(', ')

feature_counts = {}

# Iteriere über jedes DataFrame in der Liste
for df in dataframes:
    df['feature_names'] = df['feature_names'].str.split(', ')
    for index, row in df.iterrows():
        features = row['feature_names']
        if isinstance(features, list):
            for feature in features:
                if feature in feature_counts:
                    feature_counts[feature] += 1
                else:
                    feature_counts[feature] = 1

In [5]:
#Heart Daten satz = 320.000 Diabetes Datensatz = 250.000 Bank Datensatz = 45.211

# Richtige Anzahl der Samples in Daten eintragen


df_1['number_of_instances'] = 320000 * (1 - df_1['reduction_percentage'] / 100)
df_2['number_of_instances'] =  320000 * (1 - df_2['reduction_percentage'] / 100)
df_3['number_of_instances'] =  320000 * (1 - df_3['reduction_percentage'] / 100)

df_4['number_of_instances'] = 250000 * (1 - df_4['reduction_percentage'] / 100)
df_5['number_of_instances'] = 250000 * (1 - df_5['reduction_percentage'] / 100)
df_6['number_of_instances'] = 250000 * (1 - df_6['reduction_percentage'] / 100)
df_8['number_of_instances'] = 250000 * (1 - df_8['reduction_percentage'] / 100)
df_9['number_of_instances'] = 250000 * (1 - df_9['reduction_percentage'] / 100)

df_10['number_of_instances'] = 45211 * (1 - df_10['reduction_percentage'] / 100)
df_11['number_of_instances'] = 45211 * (1 - df_11['reduction_percentage'] / 100)
df_12['number_of_instances'] = 45211 * (1 - df_12['reduction_percentage'] / 100)
df_13['number_of_instances'] = 45211 * (1 - df_13['reduction_percentage'] / 100)
df_14['number_of_instances'] = 45211 * (1 - df_14['reduction_percentage'] / 100)

In [6]:
df_14.head()

,timestamp,project_name,run_id,duration,emissions,emissions_rate,cpu_power,gpu_power,ram_power,cpu_energy,...,ram_total_size,tracking_mode,on_cloud,pue,num_features,reduction_percentage,feature_names,num_num_features,num_cat_features,number_of_instances
0,2023-11-12T13:00:24,DecisionTree_19_features_reduced_by_0_percent0,b089c878-b567-4b5e-ae70-03abeaade72a,0.299119,1.504002e-06,0.000005,42.5,0.0,4.754379,3.483172e-06,...,12.678345,machine,N,1.0,19,0,NaN,3,10,45211.0
1,2023-11-12T13:00:26,DecisionTree_19_features_reduced_by_20_percent0,770b3004-eee9-4bd5-9821-dccecd4d942d,0.171267,8.497686e-07,0.000005,42.5,0.0,4.754379,1.969609e-06,...,12.678345,machine,N,1.0,19,20,NaN,3,10,36168.8
2,2023-11-12T13:00:28,DecisionTree_19_features_reduced_by_40_percent0,2b72544f-d62a-4ab4-a940-c8e159941119,0.132989,6.234077e-07,0.000005,42.5,0.0,4.754379,1.444711e-06,...,12.678345,machine,N,1.0,19,40,NaN,3,10,27126.6
3,2023-11-12T13:00:30,DecisionTree_19_features_reduced_by_60_percent0,20cb3715-3a20-479f-9b16-aa9e51ecb21f,0.093119,4.414532e-07,0.000005,42.5,0.0,4.754379,1.024619e-06,...,12.678345,machine,N,1.0,19,60,NaN,3,10,18084.4
4,2023-11-12T13:00:31,DecisionTree_19_features_reduced_by_80_percent0,a27f9f39-c84b-4842-a897-92226f7946d9,0.047154,2.168466e-07,0.000005,42.5,0.0,4.754379,5.048775e-07,...,12.678345,machine,N,1.0,19,80,NaN,3,10,9042.2

In [7]:
# Hinzufügen von dem verwendeten Model
model_names = {
    'random_forest': [df_4, df_10],
    'logistic_regression': [df_1, df_5, df_11],
    'knn': [df_6, df_12],
    'gaussian_nb': [df_2, df_8, df_13],
    'decision_tree': [df_3, df_9, df_14]
}

for model_name, dfs in model_names.items():
    for df in dfs:
        df.insert(0, 'model', model_name)

In [8]:
#Gesplitted nach Model
df_rdf = pd.concat([df_4, df_10])
df_lgr = pd.concat([df_1, df_5, df_11])
df_knn = pd.concat([df_6, df_12])
df_gnb = pd.concat([df_2, df_8, df_13])
df_dt = pd.concat([df_3, df_9, df_14])

In [9]:
df_knn.head()

,model,timestamp,project_name,run_id,duration,emissions,emissions_rate,cpu_power,gpu_power,ram_power,...,ram_total_size,tracking_mode,on_cloud,pue,num_features,reduction_percentage,feature_names,num_num_features,num_cat_features,number_of_instances
0,knn,2023-11-04T12:33:21,KNeighborsClassifier_21_features_reduced_by_0_...,248921ab-7f6d-442e-b02d-39e1f11036ad,0.033858,8.127720e-08,0.000002,42.5,0.0,4.754379,...,12.678345,machine,N,1.0,21,0,"[HvyAlcoholConsump, PhysHlth, DiffWalk, HighBP...",7,14,250000.0
1,knn,2023-11-04T12:33:23,KNeighborsClassifier_21_features_reduced_by_20...,7d1b4fa7-11e2-44a4-86e4-7fb66717068b,0.030485,7.134723e-08,0.000002,42.5,0.0,4.754379,...,12.678345,machine,N,1.0,21,20,"[HvyAlcoholConsump, PhysHlth, DiffWalk, HighBP...",7,14,200000.0
2,knn,2023-11-04T12:33:25,KNeighborsClassifier_21_features_reduced_by_40...,e849e3a2-2bde-48a5-b197-c39cc036711c,0.033078,8.248760e-08,0.000002,42.5,0.0,4.754379,...,12.678345,machine,N,1.0,21,40,"[HvyAlcoholConsump, PhysHlth, DiffWalk, HighBP...",7,14,150000.0
3,knn,2023-11-04T12:33:27,KNeighborsClassifier_21_features_reduced_by_60...,a73a3318-1ebf-4474-8100-7f501524ba87,0.027587,5.603620e-08,0.000002,42.5,0.0,4.754379,...,12.678345,machine,N,1.0,21,60,"[HvyAlcoholConsump, PhysHlth, DiffWalk, HighBP...",7,14,100000.0
4,knn,2023-11-04T12:33:29,KNeighborsClassifier_21_features_reduced_by_80...,2b0cc461-5bcd-4fcf-b78c-0a1933c0ee7a,0.016051,2.429760e-08,0.000002,42.5,0.0,4.754379,...,12.678345,machine,N,1.0,21,80,"[HvyAlcoholConsump, PhysHlth, DiffWalk, HighBP...",7,14,50000.0

In [10]:
# Reduzieren der Eingabeparams für das Modell und Analyse
selected_columns = ['energy_consumed', 'num_num_features', 'num_cat_features', 'number_of_instances']

df_rdf = df_rdf[selected_columns]
df_lgr = df_lgr[selected_columns]
df_knn = df_knn[selected_columns]
df_gnb = df_gnb[selected_columns]
df_dt = df_dt[selected_columns]

In [11]:
df_gnb.head()

   energy_consumed  num_num_features  num_cat_features  number_of_instances
0     1.369617e-06                 4                13             320000.0
1     1.083680e-06                 4                13             256000.0
2     9.345252e-07                 4                13             192000.0
3     5.141165e-07                 4                13             128000.0
4     3.445230e-07                 4                13              64000.0

In [12]:
df_knn.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2000 entries, 0 to 949
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   energy_consumed      2000 non-null   float64
 1   num_num_features     2000 non-null   int64
 2   num_cat_features     2000 non-null   int64
 3   number_of_instances  2000 non-null   float64
dtypes: float64(2), int64(2)
memory usage: 78.1 KB

In [13]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

df_temp = df_rdf


X = df_temp.drop(['energy_consumed'], axis=1)  # Features
y = df_temp['energy_consumed']  # Zielvariable

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

In [14]:
X_train

array([[ 0.65632083,  1.75860832,  0.10401209],
       [ 1.14886929,  0.96285795,  1.96917233],
       [-0.82132456, -0.62864279, -0.51770799],
       ...,
       [ 2.13396622,  0.96285795,  1.96917233],
       [ 0.16377236,  0.4323577 , -1.02699372],
       [-1.31387303, -0.62864279, -0.68969069]])

# Model Training

In [15]:
import numpy as np
from sklearn.metrics import mean_squared_error, r2_score

In [19]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
import joblib
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

In [22]:
import numpy as np

# Define datasets with names
datasets = {'df_rdf': df_rdf, 'df_lgr': df_lgr, 'df_knn': df_knn, 'df_gnb': df_gnb, 'df_dt': df_dt}

# Hyperparameter-Optimierung mit GridSearchCV
param_grid = {
    'n_estimators': [50, 100, 150],
    'min_samples_leaf': [1, 2, 4],
    'min_samples_split': [2, 5, 10],
    'max_features': ['auto', 'sqrt', 'log2'],
    'max_samples': [None, 0.5, 0.8]
}

for name, df_temp in datasets.items():
    X = df_temp.drop(['energy_consumed'], axis=1)
    y = df_temp['energy_consumed']

    print(f'Dataset name: {name}')

    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

    grid_search = GridSearchCV(RandomForestRegressor(), param_grid, cv=5, scoring='neg_mean_squared_error', n_jobs=-1)
    grid_search.fit(X_train, y_train)

    best_model = grid_search.best_estimator_
    best_model.fit(X_train, y_train)

    # Modell exportieren
    model_filename = f'best_model_{name}.pkl'
    joblib.dump(best_model, model_filename)

    # Modell testen
    X_test_sample = np.array([12, 34, 340000]).reshape(1, -1)
    X_test_sample = scaler.transform(X_test_sample)
    X_test_sample2 = np.array([12, 34, 12]).reshape(1, -1)
    X_test_sample2 = scaler.transform(X_test_sample2)
    X_test_sample3 = np.array([5, 10, 12]).reshape(1, -1)
    X_test_sample3 = scaler.transform(X_test_sample3)
    X_test_sample4 = np.array([5, 5, 12]).reshape(1, -1)
    X_test_sample4 = scaler.transform(X_test_sample4)
    X_test_sample5 = np.array([12, 34, 20000]).reshape(1, -1)
    X_test_sample5 = scaler.transform(X_test_sample5)
    X_test_sample6 = np.array([12, 34, 60000]).reshape(1, -1)
    X_test_sample6 = scaler.transform(X_test_sample6)
    predictions = best_model.predict(X_test_sample)
    print(f'Modell {name}: Vorhersage für X_test_sample: {predictions}')
    predictions2 = best_model.predict(X_test_sample2)
    print(f'Modell {name}: Vorhersage für X_test_sample2: {predictions2}')
    predictions3 = best_model.predict(X_test_sample3)
    print(f'Modell {name}: Vorhersage für X_test_sample3: {predictions3}')
    predictions4 = best_model.predict(X_test_sample4)
    print(f'Modell {name}: Vorhersage für X_test_sample4: {predictions4}')
    predictions5 = best_model.predict(X_test_sample5)
    print(f'Modell {name}: Vorhersage für X_test_sample5: {predictions5}')
    predictions6 = best_model.predict(X_test_sample6)
    print(f'Modell {name}: Vorhersage für X_test_sample6: {predictions6}')

    # Berechne und printe Metriken
    y_pred = best_model.predict(X_test)
    r2 = r2_score(y_test, y_pred)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    mae = mean_absolute_error(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)

    print(f'R2 Score: {r2}')
    print(f'RMSE: {rmse}')
    print(f'MAE: {mae}')
    print(f'MSE: {mse}\n')

Dataset name: df_rdf

/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_forest.py:413: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features=1.0` or remove this parameter as it is also the default value for RandomForestRegressors and ExtraTreesRegressors.
  warn(
/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_forest.py:413: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features=1.0` or remove this parameter as it is also the default value for RandomForestRegressors and ExtraTreesRegressors.
  warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

Modell df_rdf: Vorhersage für X_test_sample: [0.00029818]
Modell df_rdf: Vorhersage für X_test_sample2: [4.60067322e-05]
Modell df_rdf: Vorhersage für X_test_sample3: [3.85498395e-05]
Modell df_rdf: Vorhersage für X_test_sample4: [3.92086776e-05]
Modell df_rdf: Vorhersage für X_test_sample5: [4.71789634e-05]
Modell df_rdf: Vorhersage für X_test_sample6: [4.89561156e-05]
R2 Score: 0.9827241294469247
RMSE: 8.652405348829766e-06
MAE: 5.811618856166354e-06
MSE: 7.486411832045794e-11

Dataset name: df_lgr

/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_forest.py:413: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features=1.0` or remove this parameter as it is also the default value for RandomForestRegressors and ExtraTreesRegressors.
  warn(
/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_forest.py:413: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features=1.0` or remove this parameter as it is also the default value for RandomForestRegressors and ExtraTreesRegressors.
  warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

Modell df_lgr: Vorhersage für X_test_sample: [6.49655963e-06]
Modell df_lgr: Vorhersage für X_test_sample2: [1.56458944e-05]
Modell df_lgr: Vorhersage für X_test_sample3: [1.56458944e-05]
Modell df_lgr: Vorhersage für X_test_sample4: [1.2819527e-05]
Modell df_lgr: Vorhersage für X_test_sample5: [2.72867143e-05]
Modell df_lgr: Vorhersage für X_test_sample6: [1.49027522e-06]
R2 Score: 0.9666311425703609
RMSE: 3.8275593595530965e-06
MAE: 2.087482046376643e-06
MSE: 1.465021065090251e-11

Dataset name: df_knn

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

Modell df_knn: Vorhersage für X_test_sample: [5.157239e-07]
Modell df_knn: Vorhersage für X_test_sample2: [1.42468533e-07]
Modell df_knn: Vorhersage für X_test_sample3: [1.77427231e-06]
Modell df_knn: Vorhersage für X_test_sample4: [1.42447718e-06]
Modell df_knn: Vorhersage für X_test_sample5: [1.45056274e-07]
Modell df_knn: Vorhersage für X_test_sample6: [1.49641307e-07]
R2 Score: 0.8520597447954572
RMSE: 8.813048687577106e-07
MAE: 4.581908523766373e-07
MSE: 7.766982716960455e-13

Dataset name: df_gnb

/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_forest.py:413: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features=1.0` or remove this parameter as it is also the default value for RandomForestRegressors and ExtraTreesRegressors.
  warn(
/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_forest.py:413: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features=1.0` or remove this parameter as it is also the default value for RandomForestRegressors and ExtraTreesRegressors.
  warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

Modell df_gnb: Vorhersage für X_test_sample: [2.0241984e-06]
Modell df_gnb: Vorhersage für X_test_sample2: [1.90808418e-07]
Modell df_gnb: Vorhersage für X_test_sample3: [1.90808418e-07]
Modell df_gnb: Vorhersage für X_test_sample4: [1.59448907e-07]
Modell df_gnb: Vorhersage für X_test_sample5: [2.26491074e-07]
Modell df_gnb: Vorhersage für X_test_sample6: [4.26711886e-07]
R2 Score: 0.7710300828572414
RMSE: 2.0684487835529155e-07
MAE: 1.3936097102266928e-07
MSE: 4.278480370181536e-14

Dataset name: df_dt

/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_forest.py:413: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features=1.0` or remove this parameter as it is also the default value for RandomForestRegressors and ExtraTreesRegressors.
  warn(
/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_forest.py:413: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features=1.0` or remove this parameter as it is also the default value for RandomForestRegressors and ExtraTreesRegressors.
  warn(

Modell df_dt: Vorhersage für X_test_sample: [2.48857913e-05]
Modell df_dt: Vorhersage für X_test_sample2: [2.75153693e-06]
Modell df_dt: Vorhersage für X_test_sample3: [1.8994901e-06]
Modell df_dt: Vorhersage für X_test_sample4: [1.37450258e-06]
Modell df_dt: Vorhersage für X_test_sample5: [2.81319979e-06]
Modell df_dt: Vorhersage für X_test_sample6: [5.60769043e-06]
R2 Score: 0.9198582545544792
RMSE: 1.2764697609358977e-06
MAE: 8.074016934704885e-07
MSE: 1.629375050583748e-12

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(